/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedIncomeRouteImport } from './routes/_authenticated/income'
import { Route as AuthenticatedPersonalExpensesRouteImport } from './routes/_authenticated/personal-expenses'
import { Route as AuthenticatedReceivablesRouteImport } from './routes/_authenticated/receivables'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedReportsDailyRouteImport } from './routes/_authenticated/reports.daily'
import { Route as AuthenticatedReportsMonthlyRouteImport } from './routes/_authenticated/reports.monthly'
import { Route as AuthenticatedReportsYearlyRouteImport } from './routes/_authenticated/reports.yearly'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeRoute = AuthenticatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPersonalExpensesRoute =
  AuthenticatedPersonalExpensesRouteImport.update({
    id: '/personal-expenses',
    path: '/personal-expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceivablesRoute =
  AuthenticatedReceivablesRouteImport.update({
    id: '/receivables',
    path: '/receivables',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsDailyRoute =
  AuthenticatedReportsDailyRouteImport.update({
    id: '/reports/daily',
    path: '/reports/daily',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsMonthlyRoute =
  AuthenticatedReportsMonthlyRouteImport.update({
    id: '/reports/monthly',
    path: '/reports/monthly',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsYearlyRoute =
  AuthenticatedReportsYearlyRouteImport.update({
    id: '/reports/yearly',
    path: '/reports/yearly',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/personal-expenses': typeof AuthenticatedPersonalExpensesRoute
  '/receivables': typeof AuthenticatedReceivablesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/reports/yearly': typeof AuthenticatedReportsYearlyRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/personal-expenses': typeof AuthenticatedPersonalExpensesRoute
  '/receivables': typeof AuthenticatedReceivablesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/': typeof AuthenticatedIndexRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/reports/yearly': typeof AuthenticatedReportsYearlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/income': typeof AuthenticatedIncomeRoute
  '/_authenticated/personal-expenses': typeof AuthenticatedPersonalExpensesRoute
  '/_authenticated/receivables': typeof AuthenticatedReceivablesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/_authenticated/reports/monthly': typeof AuthenticatedReportsMonthlyRoute
  '/_authenticated/reports/yearly': typeof AuthenticatedReportsYearlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/expenses'
    | '/income'
    | '/personal-expenses'
    | '/receivables'
    | '/settings'
    | '/transactions'
    | '/transfers'
    | '/reports/daily'
    | '/reports/monthly'
    | '/reports/yearly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/accounts'
    | '/expenses'
    | '/income'
    | '/personal-expenses'
    | '/receivables'
    | '/settings'
    | '/transactions'
    | '/transfers'
    | '/'
    | '/reports/daily'
    | '/reports/monthly'
    | '/reports/yearly'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/expenses'
    | '/_authenticated/income'
    | '/_authenticated/personal-expenses'
    | '/_authenticated/receivables'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/_authenticated/transfers'
    | '/_authenticated/'
    | '/_authenticated/reports/daily'
    | '/_authenticated/reports/monthly'
    | '/_authenticated/reports/yearly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income': {
      id: '/_authenticated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthenticatedIncomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personal-expenses': {
      id: '/_authenticated/personal-expenses'
      path: '/personal-expenses'
      fullPath: '/personal-expenses'
      preLoaderRoute: typeof AuthenticatedPersonalExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receivables': {
      id: '/_authenticated/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof AuthenticatedReceivablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/daily': {
      id: '/_authenticated/reports/daily'
      path: '/reports/daily'
      fullPath: '/reports/daily'
      preLoaderRoute: typeof AuthenticatedReportsDailyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/monthly': {
      id: '/_authenticated/reports/monthly'
      path: '/reports/monthly'
      fullPath: '/reports/monthly'
      preLoaderRoute: typeof AuthenticatedReportsMonthlyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/yearly': {
      id: '/_authenticated/reports/yearly'
      path: '/reports/yearly'
      fullPath: '/reports/yearly'
      preLoaderRoute: typeof AuthenticatedReportsYearlyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedIncomeRoute: typeof AuthenticatedIncomeRoute
  AuthenticatedPersonalExpensesRoute: typeof AuthenticatedPersonalExpensesRoute
  AuthenticatedReceivablesRoute: typeof AuthenticatedReceivablesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReportsDailyRoute: typeof AuthenticatedReportsDailyRoute
  AuthenticatedReportsMonthlyRoute: typeof AuthenticatedReportsMonthlyRoute
  AuthenticatedReportsYearlyRoute: typeof AuthenticatedReportsYearlyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedIncomeRoute: AuthenticatedIncomeRoute,
  AuthenticatedPersonalExpensesRoute: AuthenticatedPersonalExpensesRoute,
  AuthenticatedReceivablesRoute: AuthenticatedReceivablesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReportsDailyRoute: AuthenticatedReportsDailyRoute,
  AuthenticatedReportsMonthlyRoute: AuthenticatedReportsMonthlyRoute,
  AuthenticatedReportsYearlyRoute: AuthenticatedReportsYearlyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
